package uk.ac.ed.plasmo.persistence;

//Generated Apr 15, 2010 8:34:52 AM by Hibernate Tools 3.2.4.GA

/**
 * RefGroup generated by hbm2java
 */
public class RefGroup implements java.io.Serializable {

	private int grpOid;
	private String grpName;
	private String grpDescription;
	private boolean selected = false;

	public RefGroup() {
	}

	public RefGroup(int grpOid, String grpName) {
		this.grpOid = grpOid;
		this.grpName = grpName;
	}

	public RefGroup(int grpOid, String grpName, String grpDescription) {
		this.grpOid = grpOid;
		this.grpName = grpName;
		this.grpDescription = grpDescription;
	}

	public int getGrpOid() {
		return this.grpOid;
	}

	public void setGrpOid(int grpOid) {
		this.grpOid = grpOid;
	}

	public String getGrpName() {
		return this.grpName;
	}

	public void setGrpName(String grpName) {
		this.grpName = grpName;
	}

	public String getGrpDescription() {
		return this.grpDescription;
	}

	public void setGrpDescription(String grpDescription) {
		this.grpDescription = grpDescription;
	}
	
	public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		this.selected = selected;
	}

}